AWSTemplateFormatVersion: '2010-09-09'
Description: Pipeline using CodePipeline and CodeBuild for continuous delivery of a single-page application to S3
Parameters:
  HostedZoneID:
    Description: The Hosted Zone ID in which to create the website DNS record
    Type: AWS::Route53::HostedZone::Id
    Default: Z02391713K5ZLP1KOWV0O
  WebsiteAddress:
    Description: The web address to host the website at. Must be a subdomain of the hostedzone domain.
    Type: String
    Default: master3.account-0.aws-tests.skyworkz.nl
  GitHubUser:
    Type: String
    Description: GitHub User
    Default: rohijain
  GitHubRepo:
    Type: String
    Description: GitHub Repo to pull from. Only the Name. not the URL
    Default: NewsWebsite09
  GitHubBranch:
    Type: String
    Description: GitHub Branch
    Default: master
  GitHubToken:
    Description: Github OAuth Token
    Type: AWS::SSM::Parameter::Value<String>
    Default: /service/sam-app/github/token
  BuildType:
    Type: String
    Default: LINUX_CONTAINER
    Description: The build container type to use for building the app
  BuildComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL
    Description: The build compute type to use for building the app
  BuildImage:
    Type: String
    Default: aws/codebuild/ubuntu-base:14.04
    Description: The build image to use for building the app
Mappings:
  S3HostingZoneMap:
    us-east-1:
      S3HostingZone: "Z3AQBSTGFYJSTF"
      S3HostingEndpoint: "s3-website-us-east-1.amazonaws.com"
    us-east-2:
      S3HostingZone: "Z2O1EMRO9K5GLX"
      S3HostingEndpoint: "s3-website.us-east-2.amazonaws.com"
    us-west-1:
      S3HostingZone: "Z2F56UZL2M1ACD"
      S3HostingEndpoint: "s3-website-us-west-1.amazonaws.com"
    us-west-2:
      S3HostingZone: "Z3BJ6K6RIION7M"
      S3HostingEndpoint: "s3-website-us-west-2.amazonaws.com"
    ca-central-1:
      S3HostingZone: "Z1QDHH18159H29"
      S3HostingEndpoint: "s3-website.ca-central-1.amazonaws.com"
    ap-south-1:
      S3HostingZone: "Z11RGJOFQNVJUP"
      S3HostingEndpoint: "s3-website.ap-south-1.amazonaws.com"
    ap-northeast-1:
      S3HostingZone: "Z2M4EHUR26P7ZW"
      S3HostingEndpoint: "s3-website-ap-northeast-1.amazonaws.com"
    ap-northeast-2:
      S3HostingZone: "Z3W03O7B5YMIYP"
      S3HostingEndpoint: "s3-website.ap-northeast-2.amazonaws.com"
    ap-southeast-1:
      S3HostingZone: "Z3O0J2DXBE1FTB"
      S3HostingEndpoint: "s3-website-ap-southeast-1.amazonaws.com"
    ap-southeast-2:
      S3HostingZone: "Z1WCIGYICN2BYD"
      S3HostingEndpoint: "s3-website-ap-southeast-2.amazonaws.com"
    eu-central-1:
      S3HostingZone: "Z21DNDUVLTQW6Q"
      S3HostingEndpoint: s3-website.eu-central-1.amazonaws.com
    eu-west-1:
      S3HostingZone: "Z1BKCTXD74EZPE"
      S3HostingEndpoint: "s3-website-eu-west-1.amazonaws.com"
    eu-west-2:
      S3HostingZone: "Z3GKZC51ZF0DB4"
      S3HostingEndpoint: "s3-website.eu-west-2.amazonaws.com"
    sa-east-1:
      S3HostingZone: "Z31GFT0UA1I2HV"
      S3HostingEndpoint: "s3-website-sa-east-1.amazonaws.com"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "GitHub Configuration"
        Parameters:
          - GitHubToken
          - GitHubUser
          - GitHubRepo
          - GitHubBranch
      - Label:
          default: "Build Configuration"
        Parameters:
          - BuildType
          - BuildComputeType
          - BuildImage
    ParameterLabels:
      GitHubToken:
        default: GitHub OAuth2 Token
      GitHubUser: 
        default: GitHub User/Org Name
      GitHubRepo: 
        default: GitHub Repository Name
      GitHubBranch: 
        default: GitHub Branch Name
      BuildType: 
        default: CodeBuild type
      BuildComputeType: 
        default: CodeBuild instance type
      BuildImage: 
        default: CodeBuild image
        

Resources:
####    ###    ##     ## 
 ##    ## ##   ###   ### 
 ##   ##   ##  #### #### 
 ##  ##     ## ## ### ## 
 ##  ######### ##     ## 
 ##  ##     ## ##     ## 
#### ##     ## ##     ## 
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: codebuild-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
          Version: '2012-10-17'
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: codepipeline-service
        PolicyDocument:
          Statement:
          - Action:
            - codebuild:*
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:PutObject
            Resource:
            - arn:aws:s3:::codepipeline*
            Effect: Allow
          - Action:
            - s3:*
            - cloudformation:*
            - iam:PassRole
            Resource: "*"
            Effect: Allow
          Version: '2012-10-17'
  SiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Statement:
          -
            Sid: "PublicReadForS3Website"
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  -
                    Ref: "SiteBucket"
                  - "/*"
            Principal: "*"
  SiteBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref WebsiteAddress
      WebsiteConfiguration:
        ErrorDocument: "404.html"
        IndexDocument: "index.html"
  R53Record:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Comment: "CNAME to S3-Website"
      HostedZoneId: !Ref HostedZoneID
      Type: A
      Name: !Ref WebsiteAddress
      AliasTarget:
        DNSName: !FindInMap [ S3HostingZoneMap, !Ref "AWS::Region", "S3HostingEndpoint" ]
        HostedZoneId: !FindInMap [ S3HostingZoneMap, !Ref "AWS::Region", "S3HostingZone" ]

  PipelineBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
  CodeBuildDeploySite:
    Type: AWS::CodeBuild::Project
    DependsOn: CodeBuildRole
    Properties:
      Name: !Sub ${AWS::StackName}-DeploySite
      Description: Deploy site to S3
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref BuildType
        ComputeType: !Ref BuildComputeType
        Image: !Sub ${BuildImage}
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            post_build:
              commands:
                - aws s3 cp --recursive --acl public-read ./ s3://${SiteBucket}/ 
          artifacts:
            type: zip
            files:
              - ./index.html
      TimeoutInMinutes: 10
      
########  #### ########  ######## ##       #### ##    ## ######## 
##     ##  ##  ##     ## ##       ##        ##  ###   ## ##       
##     ##  ##  ##     ## ##       ##        ##  ####  ## ##       
########   ##  ########  ######   ##        ##  ## ## ## ######   
##         ##  ##        ##       ##        ##  ##  #### ##       
##         ##  ##        ##       ##        ##  ##   ### ##       
##        #### ##        ######## ######## #### ##    ## ########
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
      - Name: Source
        Actions:
        - InputArtifacts: []
          Name: Source
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: '1'
            Provider: GitHub
          OutputArtifacts:
          - Name: SourceArtifacts 
          Configuration:
            Owner: !Ref GitHubUser
            Repo: !Ref GitHubRepo
            Branch: !Ref GitHubBranch
            OAuthToken: !Ref GitHubToken
          RunOrder: 1
      - Name: Deploy
        Actions:
        - Name: Artifact
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          InputArtifacts:
          - Name: SourceArtifacts 
          OutputArtifacts:
          - Name: DeploymentArtifacts
          Configuration:
            ProjectName: !Ref CodeBuildDeploySite
          RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineBucket
Outputs:
  PipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
    Description: CodePipeline URL
  SiteUrl:
    Value: !GetAtt [SiteBucket, WebsiteURL]
    Description: S3 Website URL
  WebsiteURL:
    Value: !GetAtt SiteBucket.WebsiteURL
    Description: URL for website hosted on S3